Controllers/AbilityController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebUI.Data.Abstract;
using WebUI.Entity;

namespace WebUI.Controllers
{
    [Authorize]
    public class AbilityController : Controller
    {
        private IAbilityRepository _abilityRepository;
        public AbilityController(IAbilityRepository abilityRepository)
        {
            _abilityRepository = abilityRepository;
        }
        [Route("panel/ability")]
        public IActionResult Index()
        {
            var data = _abilityRepository.GetAll();
            return View(data);
        }
        [Route("panel/ability/edit")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var data = _abilityRepository.GetById(id);
            return View(data);
        }
        [Route("panel/ability/edit")]
        [HttpPost]
        public IActionResult Edit(Ability ability)
        {
            if (ModelState.IsValid)
            {               
                _abilityRepository.SaveAbility(ability);
                return RedirectToAction("Index");
            }
            return View(ability);
        }
        [Route("panel/ability/delete")]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_abilityRepository.GetById(id));
        }
        [Route("panel/ability/delete")]
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int AbilityId)
        {
            _abilityRepository.DeleteAbility(AbilityId);
            return RedirectToAction("Index");
        }
        [Route("panel/ability/create")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [Route("panel/ability/create")]
        [HttpPost]
        public IActionResult Create(Ability entity)
        {
            if (ModelState.IsValid)
            {
                _abilityRepository.SaveAbility(entity);
                return RedirectToAction("Index");
            }
            return View(entity);
        }

    }
}

Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebUI.Data.Abstract;
using WebUI.Entity;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class BlogController : Controller
    {
        private ISocialRepository _socialRepository;
        private IAbilityRepository _abilityRepository;
        private IProjectRepository _projectRepository;
        private IPostRepository _postRepository;
        private IPersonalSettingRepository _personalSettingRepository;
        private ISiteSettingRepository _siteSettingRepository;
        private ICategoryRepository _categoryRepository;
        private IImageRepository _imageRepository;
        private ICommentRepository _commentRepository;
        public BlogController(ICommentRepository commentRepo, IImageRepository imageRepo, ICategoryRepository categoryRepo, ISiteSettingRepository siteSettingRepo, IPersonalSettingRepository personalSettingRepo, IPostRepository postRepo, ISocialRepository socialRepo, IAbilityRepository abilityRepo, IProjectRepository projectRepo)
        {
            _categoryRepository = categoryRepo;
            _socialRepository = socialRepo;
            _abilityRepository = abilityRepo;
            _projectRepository = projectRepo;
            _postRepository = postRepo;
            _personalSettingRepository = personalSettingRepo;
            _siteSettingRepository = siteSettingRepo;
            _imageRepository = imageRepo;
            _commentRepository = commentRepo;
        }
        public IActionResult Index()
        {
            LayoutViewBags();
            ViewBag.ability = _abilityRepository.GetAll().Where(i => i.Status == true);
            ViewBag.project = _projectRepository.GetAll().Where(i => i.Status == true);
            ViewBag.post = _postRepository.GetAll().Take(10).Where(i => i.Status == true);

            ViewBag.CoverImage = _imageRepository.GetAll().Where(i => i.IsCoverImage == true);
            return View();
        }
        [HttpGet]
        public IActionResult DetailPost(int id)
        {
            var post = _postRepository.GetById(id);

            LayoutViewBags();
            ViewBag.image = _imageRepository.GetAll().Where(i => i.PostId == id).Where(i => i.Type == 1);
            ViewBag.CoverImage = _imageRepository.GetAll().Where(i => i.IsCoverImage == true).Where(i => i.Type == 1).FirstOrDefault(i => i.PostId == id);
            ViewBag.comments = _commentRepository.GetAll().Where(i => i.PostId == id);
            return View(post);
        }
        [HttpPost]
        public IActionResult Send(int Postid, string Name, string Message)
        {
            Comment comment = new Comment();
            comment.PostId = Postid;
            comment.Name = Name;
            comment.Content = Message;
            comment.Date = DateTime.Now;
            comment.Status = true;
            _commentRepository.AddComment(comment);
            return RedirectToAction("detailpost", new { id = Postid });
        }
        public void LayoutViewBags()
        {
            ViewBag.personal = _personalSettingRepository.GetById(1);
            ViewBag.site = _siteSettingRepository.GetById(1);
            ViewBag.social = _socialRepository.GetAll();
            ViewBag.category = _categoryRepository.GetAll();
        }
        [Route("blog/projects")]
        public IActionResult Projects()
        {
            LayoutViewBags();
            ViewBag.CoverImage = _imageRepository.GetAll().Where(i => i.IsCoverImage == true);

            var projects = _projectRepository.GetAll().Where(i => i.Status == true);
            return View(projects);
        }
        [Route("blog/categories")]
        public IActionResult Categories(int id)
        {
            ViewBag.CoverImage = _imageRepository.GetAll().Where(i => i.IsCoverImage == true);
            var model = _postRepository.GetAll().Where(i => i.CatId == id);
            LayoutViewBags();
            return View(model);
        }
        [Route("blog/project/detail")]
        public IActionResult DetailProject(int id)
        {
            var project = _projectRepository.GetById(id);

            LayoutViewBags();
            ViewBag.image = _imageRepository.GetAll().Where(i => i.PostId == id).Where(i => i.Type == 2);
            ViewBag.CoverImage = _imageRepository.GetAll().Where(i => i.IsCoverImage == true).Where(i => i.Type == 2).FirstOrDefault(i => i.PostId == id);

            return View(project);
        }
    }
}

Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebUI.Data.Abstract;
using WebUI.Entity;

namespace WebUI.Controllers
{
    public class CommentController : Controller
    {
        private ICommentRepository _commentRepository;
        public CommentController(ICommentRepository commentRepo)
        {
            _commentRepository = commentRepo;
        }
        [Route("panel/comment")]
        public IActionResult Index()
        {
            return View(_commentRepository.GetAll());
        }
        [Route("panel/comment/delete")]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_commentRepository.GetById(id));
        }
        [Route("panel/comment/delete")]
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int CommentId)
        {
            _commentRepository.DeleteComment(CommentId);
            return RedirectToAction("Index");
        }
    
    

    }
}

Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebUI.Data.Abstract;
using WebUI.Entity;

namespace WebUI.Controllers
{
    public class PostController : Controller
    {
        private IPostRepository _postRepository;
        private ICategoryRepository _categoryRepository;
        private IImageRepository _imageRepository;
        public PostController(IPostRepository postRepo, ICategoryRepository catRepo, IImageRepository imgRepo)
        {
            _postRepository = postRepo;
            _categoryRepository = catRepo;
            _imageRepository = imgRepo;
        }

        public IActionResult CoverImage(int id)
        {
            _imageRepository.ChangeCoverImage(id);
            var postId = _imageRepository.GetById(id).PostId;
            return RedirectToAction("Edit", new { id = postId });
        }
        [Route("panel/post")]
        public IActionResult Index()
        {
            var data = _postRepository.GetAll();
            return View(data);
        }
        [Route("panel/post/edit")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var data = _postRepository.GetById(id);
            ViewBag.images = _imageRepository.GetAll().Where(i => i.PostId == id).Where(i => i.Type == 1);
            pullSelect();
            return View(data);
        }
        [Route("panel/post/edit")]
        [HttpPost]
        public async Task<IActionResult> Edit(Post post, IFormFile[] file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var p = "wwwroot\\img\\posts\\" + post.PostId;
                    foreach (var f in file)
                    {
                        if (f != null)
                        {
                            string ImageName = Guid.NewGuid().ToString() + Path.GetExtension(f.FileName);
                            var path = Path.Combine(Directory.GetCurrentDirectory(), p, ImageName);
                            using (var stream = new FileStream(path, FileMode.Create))
                            {
                                await f.CopyToAsync(stream);
                                _imageRepository.AddImage(ImageName, post.PostId, 1);
                            }
                        }
                    }
                }
                _postRepository.SavePost(post);
                return RedirectToAction("Index");
            }
            pullSelect();
            return View(post);
        }

        public void pullSelect()
        {
            ViewBag.Category = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
        }
        [HttpGet]
        [Route("panel/post/delete")]
        public IActionResult Delete(int id)
        {
            return View(_postRepository.GetById(id));
        }
        [Route("panel/post/delete")]
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int PostId)
        {
            _postRepository.DeletePost(PostId);
            return RedirectToAction("Index");
        }

        [Route("panel/post/deleteimage")]
        [HttpGet]
        public IActionResult DeleteImg(int id)
        {
            var postId = _imageRepository.GetById(id).PostId;
            _imageRepository.DeleteImage(id);
            return RedirectToAction("Edit", new { id = postId });
        }

        [Route("panel/post/create")]
        [HttpGet]
        public IActionResult Create()
        {
            pullSelect();
            return View();
        }
        [HttpPost]
        [Route("panel/post/create")]
        public async Task<IActionResult> Create(Post entity, IFormFile[] file)
        {

            if (ModelState.IsValid)
            {
                int max = _postRepository.GetAll().Max(i => i.PostId);
                var p = "wwwroot\\img\\posts\\" + (max + 1);
                if (!Directory.Exists(p))
                {
                    Directory.CreateDirectory(p);
                }
                int x = file.Length;
                foreach (var f in file)
                {
                    if (f != null)
                    {
                       
                        string ImageName = Guid.NewGuid().ToString() + Path.GetExtension(f.FileName);
                        var path = Path.Combine(Directory.GetCurrentDirectory(), p, ImageName);
                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await f.CopyToAsync(stream);
                            _imageRepository.AddImage(ImageName, (max + 1), 1);
                        }
                    }
                }
                _postRepository.SavePost(entity);

                return RedirectToAction("Index");
            }
            pullSelect();
            return View(entity);
        }
    }
}

Views/Shared/_BlogLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous" />

    <link rel="stylesheet" href="~/css/contact.css" />
    <link rel="stylesheet" href="~/css/footer.css" />
    <link rel="stylesheet" href="~/css/blog.css" />

    <title>@ViewData["Title"]</title>
</head>
<body id="body">
    <div class="header">


        <header>
            <div class="dd31ss"></div>
            <nav class="nav nav-open navbar-k" id="navbar-k">
                <div class="container">
                    <div class="navTop">
                        <div class="nav-left">
                            <a asp-controller="Blog" asp-action="Index" class="logo">KEREM ÇELİK</a>
                        </div>
                        <div id="nav-right" class="nav-right">

                            <a href="javascript:;" class="nav-icon" id="nav-icon" onclick="menuFunc()">
                                <i class="fa fa-bars"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
    </div>
    <div id="menu" class="menu">
        <div class="container d-flex">
            <div class="category">
                <ul class="mul">
                    <li class="mli"><a asp-controller="Blog" asp-action="Index" class="">Ana Sayfa</a></li>
                    <li class="mli">
                        <a class="collapsed" href="#ctg" data-toggle="collapse">
                            Kategoriler
                            <span class="caret"></span>
                        </a>
                        <ul class="ctgul collapse" id="ctg">
                            @foreach (var item in ViewBag.category)
                            {
                                <li class="mli" data-parent="#ctg"><a asp-controller="Blog" asp-action="Categories" asp-route-id="@item.CategoryId">@item.Name</a></li>
                            }
                        </ul>
                    </li>



                    <li class="mli"><a asp-controller="Blog" asp-action="Projects" class="">Projects</a></li>
                    <li class="mli"><a asp-controller="Contact" asp-action="Index" class="">Contact</a>   </li>
                </ul>

            </div>
        </div>
    </div>

    <main id="main" role="main">
        <div class="container mt-3">
                <div class="row">
                    <div class="col-md-8">
                        @RenderBody()
                    </div>
                    <div class="col-md-4">
                        <div class="card">
                            <h5 class="card-header">Search</h5>
                            <div class="card-body">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search for...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-secondary" type="button">Go!</button>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="card my-4">
                            <h5 class="card-header">Categories</h5>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-12">

                                        <ul class="list-unstyled mb-0">
                                            @foreach (var item in ViewBag.category)
                                            {
                                                <li>
                                                    <a asp-controller="Blog" asp-action="Categories" asp-route-id="@item.CategoryId">@item.Name</a>
                                                </li>
                                            }
                                        </ul>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        <partial name="_Footer" />
    </main>
    <!-- Optional JavaScript -->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
    <script src="~/js/blog.js"></script>


</body>
</html>

Views/Shared/_Footer.cshtml
<footer class="page-footer font-small teal">
    <!-- Footer Text -->
    <div class="container">
        <!-- Grid row -->
        <div class="ft-left">
            <div class="social-media">
                <p> <strong class="footer-title ">Sosyal Medya</strong></p>
                @foreach (var item in ViewBag.social)
                {
                    <a class="text-primary" href="@item.Link" target="_blank">@Html.Raw(item.Icon)</a>
                }

                <br>
                <br>
            </div>
            <div class="inf-box">
                <p> <strong class="footer-title">İletişim Bilgileri</strong></p>

                <p class="fs15">@ViewBag.personal.Degree & KRX </p>
                <p class="fs15">@ViewBag.personal.Email</p>
                <p class="fs15">@ViewBag.personal.Phone</p>


            </div>



        </div>
        <div class="ft-right">
            <div class="description">
                <p class="fs15"> <strong class="footer-title">Özet</strong></p>
                <p class="fs15">Adım Kerem ÇELİK, Bilgisayar Eğitmeni ve Bilgisayar Yazılımcısıyım. 8 yıldır C# dilinde çeşitli yazılımlar geliştirdim. 2019 yılından itibaren web yazılımları geliştirmeye başladım.</p>

            </div>
            <div class="copyright">
                <p> <strong class="footer-title">Copyright</strong></p>
                <p class="fs15">© 2020 @ViewBag.personal.Name & <a href="@ViewBag.site.SiteName">@ViewBag.site.SiteName</a></p>
                <p class="fs15"><strong class="footer-title fs15">Created By</strong> @ViewBag.personal.Name</p>
            </div>
        </div>
        <!-- Grid row -->

    </div>
</footer>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/login.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_PanelLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Navbar</a>

        </nav>
    </header>
    <div class="container mt-3">
        <main role="main" class="pb-3">
            <div class="row no-gutters">
                <div class="col-md-3">
                    <partial name="_SideBar" />
                </div>
                <div class="col-md-9">
                    @RenderBody()
                </div>
            </div>

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_PersonalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-58156243-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-58156243-2');
    </script>

    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.css" integrity="sha256-a2tobsqlbgLsWs7ZVUGgP5IvWZsx8bTNQpzsqCSm5mk=" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/footer.css" />
    <link rel="stylesheet" href="~/css/personal.css" />
</head>
<body>
    <header>
        <nav class="nav nav-open navbar-k" id="nav">
            <div class="navTop" id="navTopId">
                <div class="nav-left">
                    <a href="#" class="logo">KEREM ÇELİK</a>
                </div>
                <div id="nav-right" class="nav-right">
                    <a asp-action="Index" asp-controller="Home" class=" active">Ana Sayfa</a>
                    <a asp-action="Index" asp-controller="Blog" class="" target="_blank">Blog</a>
                    <a href="javascript:void(0);" class="nav-icon" id="nav-icon" onclick="menuFunc()">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <main role="main">

        @RenderBody()
    </main>
    <partial name="_Footer" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
    <script src="~/js/personal.js"></script>
</body>
</html>

Views/Shared/_SideBar.cshtml
<div class="list-group">
    <a asp-controller="Home" asp-action="Index" class="list-group-item"><i class="fas fa-book"></i> Home </a>
    <a asp-controller="Post" asp-action="Index"  class="list-group-item"><i class="fas fa-feather"></i> Post Options </a>
    <a asp-controller="Project" asp-action="Index" class="list-group-item"><i class="fas fa-list"></i> Project Options </a>
    <a asp-controller="Comment" asp-action="Index" class="list-group-item"><i class="fas fa-bullhorn"></i> Comment Options </a>
    <a asp-controller="Category" asp-action="Index" class="list-group-item"><i class="fas fa-language"></i> Category Options </a>
    <a asp-controller="Ability" asp-action="Index" class="list-group-item"><i class="fas fa-language"></i> Ability Options </a>
    <a asp-controller="SocialSetting" asp-action="Index" class="list-group-item"><i class="fas fa-language"></i> Social Settings  </a>
    <a asp-controller="SiteSetting" asp-action="Index" class="list-group-item"><i class="fas fa-language"></i> Site Settings  </a>
    <a asp-controller="PersonalSetting" asp-action="Index" class="list-group-item"><i class="fas fa-language"></i> Personal Settings  </a>
</div>