Controllers/SiteSettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebUI.Data.Abstract;
using WebUI.Entity;

namespace WebUI.Controllers
{
    public class SiteSettingController : Controller
    {
        private ISiteSettingRepository _siteSettingRepository;
        public SiteSettingController(ISiteSettingRepository siteSettingRepo)
        {
            _siteSettingRepository = siteSettingRepo;
        }
        [Route("panel/setting/site")]
        [HttpGet]
        public IActionResult Index()
        {
            return View(_siteSettingRepository.GetById(1));
        }
        [Route("panel/setting/site")]
        [HttpPost]
        public IActionResult Index(SiteSetting entity)
        {
            if (ModelState.IsValid)
            {
                _siteSettingRepository.SaveSiteSetting(entity);
                return RedirectToAction("Index");
            }
            return View(entity);
        }
    }
}

Controllers/SocialSettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebUI.Data.Abstract;
using WebUI.Entity;

namespace WebUI.Controllers
{
    public class SocialSettingController : Controller
    {
        private ISocialRepository _socialRepository;
        public SocialSettingController(ISocialRepository socialRepo)
        {
            _socialRepository = socialRepo;
        }
        [Route("panel/setting/social")]
        public IActionResult Index()
        {
            return View(_socialRepository.GetAll());
        }
        [Route("panel/setting/social/edit")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var data = _socialRepository.GetById(id);
            return View(data);
        }
        [Route("panel/setting/social/edit")]
        [HttpPost]
        public IActionResult Edit(SocialSetting social)
        {
            if (ModelState.IsValid)
            {
                _socialRepository.SaveSocialSetting(social);
                return RedirectToAction("Index");
            }
            return View(social);
        }
        [Route("panel/setting/social/delete")]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_socialRepository.GetById(id));
        }
        [Route("panel/setting/social/delete")]
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int SocialId)
        {
            _socialRepository.DeleteSocialSetting(SocialId);
            return RedirectToAction("Index");
        }
        [Route("panel/setting/social/create")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [Route("panel/setting/social/create")]
        [HttpPost]
        public IActionResult Create(SocialSetting entity)
        {
            if (ModelState.IsValid)
            {
                _socialRepository.SaveSocialSetting(entity);
                return RedirectToAction("Index");
            }
            return View(entity);
        }

    }
}

Views/SocialSetting/Create.cshtml
@model SocialSetting
@{
    ViewData["Title"] = "Create";
    Layout = "_PanelLayout";
}

<div class="row">
    <div class="col-md-12 ml-3">
        <form asp-action="Create" asp-controller="SocialSetting" method="POST">
            <div class="form-group">
                <label asp-for="Name">Name</label>
                <input asp-for="Name" class="form-control" placeholder="Please enter social name" />
            </div>
            <div class="form-group">
                <label asp-for="Link">Link</label>
                <input asp-for="Link" class="form-control" placeholder="Please enter link" />
            </div>
            <div class="form-group">
                <label asp-for="Icon">Icon</label>
                <input asp-for="Icon" class="form-control" placeholder="Please enter the social icon" />
            </div>
            <div class="form-group">
                <div class="custom-control custom-switch">
                    <input type="checkbox" asp-for="Status" class="custom-control-input">
                    <label class="custom-control-label" asp-for="Status">Status</label>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
</div>

Views/SocialSetting/Delete.cshtml
@model SocialSetting
@{
    ViewData["Title"] = "Delete";
    Layout = "_PanelLayout";
}
<h2>
    <b>@Model.Name</b> isimli Sosyal medyayı silmek istiyormusunuz ?

</h2>
<form asp-controller="SiteSetting" asp-action="Delete" method="POST">
    <input type="hidden" asp-for="SocialId">
    <button type="submit" class="btn btn-primary">Delete</button>
</form>

Views/SocialSetting/Edit.cshtml
@model SocialSetting
@{
    ViewData["Title"] = "Edit";
    Layout = "_PanelLayout";
}

<div class="row">
    <div class="col-md-12 ml-3">
        <form asp-action="Edit" asp-controller="SocialSetting" method="POST">
            <input type="hidden" asp-for="SocialId">
            <div class="form-group">
                <label asp-for="Name">Name</label>
                <input asp-for="Name" class="form-control" placeholder="Please enter social name" />
            </div>
            <div class="form-group">
                <label asp-for="Link">Link</label>
                <input asp-for="Link" class="form-control" placeholder="Please enter link" />
            </div>
            <div class="form-group">
                <label asp-for="Icon">Icon</label>
                <input asp-for="Icon" class="form-control" placeholder="Please enter the social icon" />
            </div>
            <div class="form-group">
                <div class="custom-control custom-switch">
                    <input type="checkbox" asp-for="Status" class="custom-control-input">
                    <label class="custom-control-label" asp-for="Status">Status</label>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
</div>

Views/SocialSetting/Index.cshtml
@model IEnumerable<SocialSetting>
@{
    ViewData["Title"] = "Index";
    Layout = "_PanelLayout";
}

<div class="col ml-3">
    <div class="text-right mb-3">
        <a asp-controller="SocialSetting" asp-action="Create" class="btn btn-sm btn-primary">Create</a>
        <a href="/socialsetting/create" class="btn btn-sm btn-primary">Create</a>
    </div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Status</th>
                <th>Name</th>
                <th>Icon</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @if (item.Status == false)
                        {
                            <span class="badge badge-danger">Passive</span>
                        }
                        else
                        {
                            <span class="badge badge-success">Active</span>
                        }
                    </td>
                    <td>@item.Name</td>
                    <td>@Html.Raw(item.Icon)</td>
                    <td>
                        <a class="btn btn-primary btn-sm" asp-route-id="@item.SocialId" asp-action="Edit" asp-controller="SocialSetting">
                            Edit
                        </a>
                        <a class="btn btn-danger btn-sm" asp-route-id="@item.SocialId" asp-action="Delete" asp-controller="SocialSetting">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>